development:
  api_key: "prtl6749387986743898559646983194"
  polling_url: "http://partners.api.skyscanner.net/apiservices/pricing/v1.0/"
  hotel_polling_url: "http://partners.api.skyscanner.net"

production:
  api_key: "prtl6749387986743898559646983194"
  pro_api_key: "gu679068437910229598633046372465"
  polling_url: "http://partners.api.skyscanner.net/apiservices/pricing/v1.0/"
  hotel_polling_url: "http://partners.api.skyscanner.net"
