development:
  api_key: "prtl6749387986743898559646983194"
  polling_url: "http://partners.api.skyscanner.net/apiservices/pricing/v1.0/"

production:
  api_key: "gu679068437910229598633046372465"
  polling_url: "http://partners.api.skyscanner.net/apiservices/pricing/v1.0/"